apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: super-admin
      containers:
        - name: my-app-container
          image: my-app-image:latest # Replace this with your actual image name and tag
          imagePullPolicy: Always
          ports:
            - containerPort: 9000 # Change this based on your app's port
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 9000 # Change this based on your app's port
  type: ClusterIP
